import os
import json

def generate_narrative(pattern_type, accounts_involved, agent_findings, risk_score, score_breakdown):
    """
    Calls Gemini API to generate investigation narrative.
    Falls back to structured template if API fails or key missing.
    """

    # Build structured context from agent findings
    findings_text = []
    for agent in agent_findings:
        agent_name = agent.get("agent", "unknown")
        for f in agent.get("findings", []):
            findings_text.append(f"- [{agent_name}] {f.get('detail', '')}")

    findings_summary = "\n".join(findings_text) if findings_text else "No specific findings from agents."

    score_text = "\n".join(
        f"- {item['component']}: +{item['points']} pts — {item.get('basis', '')}"
        for item in score_breakdown
    )

    prompt = f"""You are a senior AML investigator at an Indian bank writing a Suspicious Transaction Report narrative for FIU-IND.

Write a concise, professional investigation narrative (3-4 paragraphs) based ONLY on the structured findings below. Do not invent facts. Do not use legal conclusions. Use formal banking language.

PATTERN TYPE: {pattern_type.replace("_", " ").upper()}
ACCOUNTS INVOLVED: {", ".join(accounts_involved)}
RISK SCORE: {risk_score}/100

AGENT FINDINGS:
{findings_summary}

SCORE BREAKDOWN:
{score_text}

Write the narrative now. Start directly with the findings. Do not include headers or bullet points."""

    api_key = os.getenv("GEMINI_API_KEY")

    if api_key:
        try:
            import google.generativeai as genai
            genai.configure(api_key=api_key)
            model = genai.GenerativeModel("gemini-1.5-flash")
            response = model.generate_content(prompt)
            narrative = response.text.strip()
            watermark = "\n\n---\n⚠ AI-ASSISTED DRAFT — This narrative was generated by FundDrishti AI. Human review and verification required before submission to FIU-IND. The investigator is the legal accountable party."
            return narrative + watermark
        except Exception as e:
            print(f"Gemini API failed: {e} — falling back to template")

    # Template fallback
    return _template_narrative(pattern_type, accounts_involved, agent_findings, risk_score, findings_summary)


def _template_narrative(pattern_type, accounts_involved, agent_findings, risk_score, findings_summary):
    account_str = ", ".join(accounts_involved[:5])
    if len(accounts_involved) > 5:
        account_str += f" and {len(accounts_involved) - 5} others"

    pattern_descriptions = {
        "structuring": "multiple accounts were identified sending amounts clustered just below the ₹10 lakh CTR reporting threshold to a common destination account within a compressed time window, indicative of coordinated structuring activity",
        "layering": "a multi-hop fund flow chain was detected wherein funds traversed multiple intermediary accounts in rapid succession with strictly increasing timestamps and minimal skimming between hops, consistent with layering typology",
        "round_trip": "a circular fund flow was detected wherein funds originated from an account, traversed intermediary accounts, and returned to the originating account within 72 hours with minimal value loss, consistent with round-tripping",
        "dormant_activation": "a cluster of accounts with no transaction activity for over 90 days were simultaneously reactivated within a 2-hour window, receiving similar fund amounts from common sources, indicative of coordinated mule account activation",
        "profile_mismatch": "significant deviation was detected between the account holder's declared customer profile and their observed transactional behavior, with behavioral features exceeding 2.5 standard deviations from the declared peer group benchmark",
    }

    description = pattern_descriptions.get(pattern_type, "suspicious fund flow activity was detected requiring further investigation")

    narrative = f"""During routine transaction monitoring, {description}. The accounts under investigation — {account_str} — were flagged by the FundDrishti automated detection system with a composite risk score of {risk_score}/100.

The following anomalies were identified through multi-agent graph analysis: {findings_summary}

Based on the above findings, the transaction activity associated with the identified accounts is assessed as suspicious and inconsistent with normal banking behavior. The pattern is consistent with known money laundering typologies as outlined in FATF guidance and RBI AML directives.

This report is being filed in accordance with the Prevention of Money Laundering Act (PMLA), 2002 and the reporting obligations under FIU-IND guidelines. The reporting entity recommends further investigation and account-level scrutiny by the competent authority.

---
⚠ AI-ASSISTED DRAFT — This narrative was generated by FundDrishti AI using structured agent findings. Human review and verification required before submission to FIU-IND. The investigator is the legal accountable party."""

    return narrative